spring.application.name=expense-tracker

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=C##EXPENSE_TRACKER
spring.datasource.password=oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.port=${PORT:8080}